name: Output Workflow
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output date and time
        run: date
      - name: Output GitHub context
        run: echo "${{ toJson(github) }}" > github_context.json
      - name: Display GitHub context file
        run: cat github_context.json
